### ISSUE TITLE
[FE] 보낸예약 list view에 거절 승낙이 있는 오류 

### ISSUE THREAD

**Issue by KangYunHo1221** [woowacourse-teams/2022-thankoo#126]
## 기능 상세
- [ ] 보낸 예약 list view item 에는 거절 승낙 -> 수정 삭제로 변경해야 함

**Comment by kwannee** [comment]
어 이거 수정하지 않았나요? 캐시 삭제 후 새로고침 한번 해보시겠어요?

**Comment by KangYunHo1221** [comment]
햇는데 후이가 이슈 안닫은듯ㅋㅋ
