### ISSUE TITLE
[FE] UX 상 살짝 서운한 점들

### ISSUE THREAD

**Issue by kwannee** [woowacourse-teams/2022-thankoo#318]
## 기능 상세
- [x] #319
<img width="377" alt="image" src="https://user-images.githubusercontent.com/41886825/185130552-6afad912-4d20-41e5-b5a4-4e95598810c7.png">

- [x] #320
- [x] 예약 수신인 본인으로 나오는 게 핵버그
- [x] 쿠폰 전송하고 보낸 쿠폰 확인하기 버튼 누르면 메인 페이지 가는데 디폴트가 `받은`이라서 `보낸 쿠폰` 바로 안보이는게 서운함
- [x] 예약 신청하기도 마찬가지 이유로 서운함

**Comment by jayjaehunchoi** [comment]
![image](https://user-images.githubusercontent.com/87312401/185148534-23b6ba81-6cd8-4eba-91f5-e51f4f216c11.jpeg)

위에가 빈게 살짝 아쉬움

**Comment by jayjaehunchoi** [comment]
![image](https://user-images.githubusercontent.com/87312401/185148864-0159dedb-9e3f-4aa3-993b-42f4feeccc16.png)

여기도 쿠폰화면처럼 받은예약 보낸예약으로 나뉘면 좋을거같음
