### ISSUE TITLE
[BE] 쿠폰 시리얼을 발급한다.

### ISSUE THREAD

**Issue by yhh1056** [woowacourse-teams/2022-thankoo#384]
## 기능 상세

가장 단순한 방식으로 구현했습니다. 흐름은 다음과 같아요.

1. 시리얼 생성 -> 쿠폰 타입, 코치, 난수(code)로 POST 요청을 통해 생성
2. QR 코드 요청 -> 시리얼을 생성할 때 난수(code)로 QR 코드를 생성합니다.
    - QR 코드 API 응답은 contentType: image/png로 응답합니다.
    - https://goqr.me/api/ <- 사용한 QR code API 입니다.
    - 같은 URL 요청은 항상 같은 QR 코드를 생성합니다.
    - 큐알을 찍으면 땡쿠페이지로 이동합니다.
    - 파라미터로 난수(code)를 함께 넘깁니다.
3. 시리얼 조회 API를 통해 시리얼의 정보를 조회합니다.
4. 시리얼 등록 API를 통해 쿠폰을 생성합니다.

---

고민 사항
다른 도메인이 시리얼을 의존하지 않도록 구현. (없어질 수도 있는 도메인)

개선 사항
1. QR코드를 요청할 때 마다 외부 API를 호출해야합니다. 개선 방법에 대해 같이 고민해보아요.
2.

**Comment by jayjaehunchoi** [comment]
https://www.baeldung.com/spring-webclient-simultaneous-calls
