### ISSUE TITLE
[BE] local 환경에서도 실행가능한 환경을 구축한다.

### ISSUE THREAD

**Issue by yhh1056** [woowacourse-teams/2022-thankoo#483]
## 필요한 이유

테스트 코드를 통해서도 피드백을 받을 수 있지만 로컬 환경에서 리액트와 스프링부트를 띄우면서 작업하는 환경도 필요하다고 느꼈어요.
현재 문제점은 외부 환경인데요. 구글 로그인의 경우만 보아도 로그인을 하기위해 GCP에서 리다이렉트도 설정해야하고 토큰을 받기까지의 작업도 매우 번거로워요.

외부 환경에 대해 영향을 받지 않는 로컬 환경을 어떻게 만들어볼 수 있을지 같이 고민해보면 좋을 것 같아요.

**Comment by jayjaehunchoi** [comment]
프론트를 함께 실행하면 문제 없지 않나용?
