### ISSUE TITLE
[BE] CouponSerial 관련 기능에 Organization 을 추가한다. 

### ISSUE THREAD

**Issue by yhh1056** [woowacourse-teams/2022-thankoo#531]
### Admin
- 회원(코치)의 id로 보유한 시리얼 정보 조회
- 시리얼 생성

### Product
- 시리얼 코드로 누구의 쿠폰인지 조회
- 시리얼 코드로 쿠폰 등록
---
Todo
- [x] 기존 리팩토링하던 코드를 가져온다.
- [x] 라라의 검증로직을 사용한다.

Admin
- [x] 시리얼을 생성할 때 조직의 id를 받아 생성한다.
  - [x] 조직이 존재하는지 검증한다. 
  - [x] 조직에 회원이 가입했는지 검증한다.
- [x] 시리얼을 조회할 때 조직의 id도 함께 조회한다.
- [x] QR 코드에 조직 id도 포함한다.
  - [x] 조직이 존재하는지 검증한다. 

Product
- [x] 시리얼을 조회할 때 조직의 id도 함께 조회한다.
  - [x] 회원이 해당 조직에 가입되어있는지 검증한다. 
- [x] 시리얼을 사용할 떄 회원이 해당 조직에 가입되어있는지 검증한다. 

---
스키마를 작성한다.
```sql
alter table coupon_serial add organization_id bigint;
```

---
### 고민 사항
어드민의 경우 path로 id를 받지않고 body로 넘기고 있는데 어떡해야할까요?
QR코드는 path로 받고있어여. 둘중 하나로 어드민에 대한 정책 정해지면 수정할게요

**Comment by jayjaehunchoi** [comment]
#523 에 이슈를 연결해주세요
