### ISSUE TITLE
[FE] 즉시사용한 쿠폰디테일이 제대로 된 날짜를 보여주도록 수정한다

### ISSUE THREAD

**Issue by KangYunHo1221** [woowacourse-teams/2022-thankoo#592]
## 기능 상세
- [ ] 즉시사용의 경우 쿠폰디테일이 현재시간을 보여주지 않고 사용한 시간을 보여주도록 변경한다.
- [ ] 즉시사용의 경우 잘못된 양식(콤마가 섞여있는) 이 보여지는 것을 막는다.

**Comment by jayjaehunchoi** [comment]
오 대박
