### ISSUE TITLE
[FE] 자동로그인 구현 

### ISSUE THREAD

**Issue by KangYunHo1221** [woowacourse-teams/2022-thankoo#68]
## 토의 후 결정해야할 사항
1. localStorage 와 Recoil state 두 군데 다 token만 저장하기,
2. localStorage는 token, Recoil state는 token, userId 두개 저장해서 각 페이지마다 token으로 통신후 recoil 상태 업데이트 해주기
3. localStorage에 token넣고, recoil Auth는 삭제한 후 storage token을 바탕으로 각 page마다 통신하기

## 기능 상세
- [ ] 최초 로그인 이후 자동로그인을 구현한다.

**Comment by kwannee** [comment]
localStorage는 token, Recoil state는 token, userId 두개 저장해서 각 페이지마다 token으로 통신후 recoil 상태 업데이트 해주기
1. 추가적으로 recoil auth에 name도 관리하도록 수정
2. 자동 로그인 시 auth 정보 최신화
3. 개인 정보 수정 시 auth 정보 최신화
